module Evergreen.Migrate.V25 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V22.Types
import Evergreen.V25.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V22.Types.FrontendModel -> ModelMigration Evergreen.V25.Types.FrontendModel Evergreen.V25.Types.FrontendMsg
frontendModel old =
    ModelMigrated
        ( Evergreen.V25.Types.Loading
            { colorTexture = Nothing
            , roughnessTexture = Nothing
            }
        , Cmd.none
        )


backendModel : Evergreen.V22.Types.BackendModel -> ModelMigration Evergreen.V25.Types.BackendModel Evergreen.V25.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V22.Types.FrontendMsg -> MsgMigration Evergreen.V25.Types.FrontendMsg Evergreen.V25.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V22.Types.ToBackend -> MsgMigration Evergreen.V25.Types.ToBackend Evergreen.V25.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V22.Types.BackendMsg -> MsgMigration Evergreen.V25.Types.BackendMsg Evergreen.V25.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V22.Types.ToFrontend -> MsgMigration Evergreen.V25.Types.ToFrontend Evergreen.V25.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_ArrowKey : Evergreen.V22.Types.ArrowKey -> Evergreen.V25.Types.ArrowKey
migrate_Types_ArrowKey old =
    case old of
        Evergreen.V22.Types.UpKey ->
            Evergreen.V25.Types.UpKey

        Evergreen.V22.Types.DownKey ->
            Evergreen.V25.Types.DownKey

        Evergreen.V22.Types.LeftKey ->
            Evergreen.V25.Types.LeftKey

        Evergreen.V22.Types.RightKey ->
            Evergreen.V25.Types.RightKey


migrate_Types_ButtonState : Evergreen.V22.Types.ButtonState -> Evergreen.V25.Types.ButtonState
migrate_Types_ButtonState old =
    case old of
        Evergreen.V22.Types.Up ->
            Evergreen.V25.Types.Up

        Evergreen.V22.Types.Down ->
            Evergreen.V25.Types.Down


migrate_Types_FrontendMsg : Evergreen.V22.Types.FrontendMsg -> Evergreen.V25.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V22.Types.WindowResized p0 p1 ->
            Evergreen.V25.Types.WindowResized p0 p1

        Evergreen.V22.Types.Tick p0 ->
            Evergreen.V25.Types.Tick p0

        Evergreen.V22.Types.MouseMoved p0 p1 ->
            Evergreen.V25.Types.MouseMoved p0 p1

        Evergreen.V22.Types.MouseDown ->
            Evergreen.V25.Types.MouseDown

        Evergreen.V22.Types.MouseUp ->
            Evergreen.V25.Types.MouseUp

        Evergreen.V22.Types.ArrowKeyChanged p0 p1 ->
            Evergreen.V25.Types.ArrowKeyChanged (p0 |> migrate_Types_ArrowKey)
                (p1 |> migrate_Types_ButtonState)

        Evergreen.V22.Types.TouchesChanged p0 ->
            Evergreen.V25.Types.TouchesChanged (p0 |> migrate_Types_TouchContact)

        Evergreen.V22.Types.JoystickTouchChanged p0 ->
            Evergreen.V25.Types.JoystickTouchChanged (p0 |> migrate_Types_TouchContact)

        Evergreen.V22.Types.ShootClicked ->
            Evergreen.V25.Types.ShootClicked

        Evergreen.V22.Types.GotPointerLock ->
            Evergreen.V25.Types.GotPointerLock

        Evergreen.V22.Types.LostPointerLock ->
            Evergreen.V25.Types.LostPointerLock

        Evergreen.V22.Types.NoOpFrontendMsg ->
            Evergreen.V25.Types.NoOpFrontendMsg


migrate_Types_TouchContact : Evergreen.V22.Types.TouchContact -> Evergreen.V25.Types.TouchContact
migrate_Types_TouchContact old =
    case old of
        Evergreen.V22.Types.OneFinger p0 ->
            Evergreen.V25.Types.OneFinger p0

        Evergreen.V22.Types.NotOneFinger ->
            Evergreen.V25.Types.NotOneFinger
