module Evergreen.Migrate.V26 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Array
import Evergreen.V25.Direction3dWire
import Evergreen.V25.Internal.Body
import Evergreen.V25.Internal.Constraint
import Evergreen.V25.Internal.Contact
import Evergreen.V25.Internal.Material
import Evergreen.V25.Internal.Matrix3
import Evergreen.V25.Internal.Shape
import Evergreen.V25.Internal.Transform3d
import Evergreen.V25.Internal.Vector3
import Evergreen.V25.Internal.World
import Evergreen.V25.Physics.Coordinates
import Evergreen.V25.Physics.World
import Evergreen.V25.Scene3d.Material
import Evergreen.V25.Scene3d.Types
import Evergreen.V25.Shapes.Convex
import Evergreen.V25.Shapes.Plane
import Evergreen.V25.Shapes.Sphere
import Evergreen.V25.Types
import Evergreen.V26.Direction3dWire
import Evergreen.V26.Internal.Body
import Evergreen.V26.Internal.Constraint
import Evergreen.V26.Internal.Contact
import Evergreen.V26.Internal.Material
import Evergreen.V26.Internal.Matrix3
import Evergreen.V26.Internal.Shape
import Evergreen.V26.Internal.Transform3d
import Evergreen.V26.Internal.Vector3
import Evergreen.V26.Internal.World
import Evergreen.V26.Physics.Coordinates
import Evergreen.V26.Physics.World
import Evergreen.V26.Scene3d.Material
import Evergreen.V26.Scene3d.Types
import Evergreen.V26.Shapes.Convex
import Evergreen.V26.Shapes.Plane
import Evergreen.V26.Shapes.Sphere
import Evergreen.V26.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V25.Types.FrontendModel -> ModelMigration Evergreen.V26.Types.FrontendModel Evergreen.V26.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V25.Types.BackendModel -> ModelMigration Evergreen.V26.Types.BackendModel Evergreen.V26.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V25.Types.FrontendMsg -> MsgMigration Evergreen.V26.Types.FrontendMsg Evergreen.V26.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V25.Types.ToBackend -> MsgMigration Evergreen.V26.Types.ToBackend Evergreen.V26.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V25.Types.BackendMsg -> MsgMigration Evergreen.V26.Types.BackendMsg Evergreen.V26.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V25.Types.ToFrontend -> MsgMigration Evergreen.V26.Types.ToFrontend Evergreen.V26.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Direction3dWire_Direction3dWire : (coordinates_old -> coordinates_new) -> Evergreen.V25.Direction3dWire.Direction3dWire coordinates_old -> Evergreen.V26.Direction3dWire.Direction3dWire coordinates_new
migrate_Direction3dWire_Direction3dWire migrate_coordinates old =
    case old of
        Evergreen.V25.Direction3dWire.Direction3dWire p0 p1 p2 ->
            Evergreen.V26.Direction3dWire.Direction3dWire p0 p1 p2


migrate_Internal_Body_Body : (data_old -> data_new) -> Evergreen.V25.Internal.Body.Body data_old -> Evergreen.V26.Internal.Body.Body data_new
migrate_Internal_Body_Body migrate_data old =
    { id = old.id
    , data = old.data |> migrate_data
    , material = old.material |> migrate_Internal_Material_Material
    , transform3d =
        old.transform3d
            |> migrate_Internal_Transform3d_Transform3d migrate_Physics_Coordinates_WorldCoordinates
                (\rec ->
                    { defines = rec.defines |> migrate_Internal_Shape_CenterOfMassCoordinates
                    }
                )
    , centerOfMassTransform3d =
        old.centerOfMassTransform3d
            |> migrate_Internal_Transform3d_Transform3d migrate_Physics_Coordinates_BodyCoordinates
                (\rec ->
                    { defines = rec.defines |> migrate_Internal_Shape_CenterOfMassCoordinates
                    }
                )
    , velocity = old.velocity |> migrate_Internal_Vector3_Vec3
    , angularVelocity = old.angularVelocity |> migrate_Internal_Vector3_Vec3
    , mass = old.mass
    , shapes = old.shapes |> List.map (migrate_Internal_Shape_Shape migrate_Internal_Shape_CenterOfMassCoordinates)
    , worldShapes = old.worldShapes |> List.map (migrate_Internal_Shape_Shape migrate_Physics_Coordinates_WorldCoordinates)
    , force = old.force |> migrate_Internal_Vector3_Vec3
    , torque = old.torque |> migrate_Internal_Vector3_Vec3
    , boundingSphereRadius = old.boundingSphereRadius
    , linearDamping = old.linearDamping
    , angularDamping = old.angularDamping
    , invMass = old.invMass
    , invInertia = old.invInertia |> migrate_Internal_Matrix3_Mat3
    , invInertiaWorld = old.invInertiaWorld |> migrate_Internal_Matrix3_Mat3
    }


migrate_Internal_Constraint_Constraint : (coordinates_old -> coordinates_new) -> Evergreen.V25.Internal.Constraint.Constraint coordinates_old -> Evergreen.V26.Internal.Constraint.Constraint coordinates_new
migrate_Internal_Constraint_Constraint migrate_coordinates old =
    case old of
        Evergreen.V25.Internal.Constraint.PointToPoint p0 p1 ->
            Evergreen.V26.Internal.Constraint.PointToPoint (p0 |> migrate_Internal_Vector3_Vec3)
                (p1 |> migrate_Internal_Vector3_Vec3)

        Evergreen.V25.Internal.Constraint.Hinge p0 p1 p2 p3 ->
            Evergreen.V26.Internal.Constraint.Hinge (p0 |> migrate_Internal_Vector3_Vec3)
                (p1 |> migrate_Internal_Vector3_Vec3)
                (p2 |> migrate_Internal_Vector3_Vec3)
                (p3 |> migrate_Internal_Vector3_Vec3)

        Evergreen.V25.Internal.Constraint.Lock p0 p1 p2 p3 p4 p5 p6 p7 ->
            Evergreen.V26.Internal.Constraint.Lock (p0 |> migrate_Internal_Vector3_Vec3)
                (p1 |> migrate_Internal_Vector3_Vec3)
                (p2 |> migrate_Internal_Vector3_Vec3)
                (p3 |> migrate_Internal_Vector3_Vec3)
                (p4 |> migrate_Internal_Vector3_Vec3)
                (p5 |> migrate_Internal_Vector3_Vec3)
                (p6 |> migrate_Internal_Vector3_Vec3)
                (p7 |> migrate_Internal_Vector3_Vec3)

        Evergreen.V25.Internal.Constraint.Distance p0 ->
            Evergreen.V26.Internal.Constraint.Distance p0


migrate_Internal_Constraint_ConstraintGroup : Evergreen.V25.Internal.Constraint.ConstraintGroup -> Evergreen.V26.Internal.Constraint.ConstraintGroup
migrate_Internal_Constraint_ConstraintGroup old =
    { bodyId1 = old.bodyId1
    , bodyId2 = old.bodyId2
    , constraints = old.constraints |> List.map (migrate_Internal_Constraint_Constraint migrate_Internal_Shape_CenterOfMassCoordinates)
    }


migrate_Internal_Contact_ContactGroup : (data_old -> data_new) -> Evergreen.V25.Internal.Contact.ContactGroup data_old -> Evergreen.V26.Internal.Contact.ContactGroup data_new
migrate_Internal_Contact_ContactGroup migrate_data old =
    { body1 = old.body1 |> migrate_Internal_Body_Body migrate_data
    , body2 = old.body2 |> migrate_Internal_Body_Body migrate_data
    , contacts = old.contacts
    }


migrate_Internal_Material_Material : Evergreen.V25.Internal.Material.Material -> Evergreen.V26.Internal.Material.Material
migrate_Internal_Material_Material old =
    old


migrate_Internal_Matrix3_Mat3 : Evergreen.V25.Internal.Matrix3.Mat3 -> Evergreen.V26.Internal.Matrix3.Mat3
migrate_Internal_Matrix3_Mat3 old =
    old


migrate_Internal_Shape_CenterOfMassCoordinates : Evergreen.V25.Internal.Shape.CenterOfMassCoordinates -> Evergreen.V26.Internal.Shape.CenterOfMassCoordinates
migrate_Internal_Shape_CenterOfMassCoordinates old =
    case old of
        Evergreen.V25.Internal.Shape.CenterOfMassCoordinates ->
            Evergreen.V26.Internal.Shape.CenterOfMassCoordinates


migrate_Internal_Shape_Shape : (coordinates_old -> coordinates_new) -> Evergreen.V25.Internal.Shape.Shape coordinates_old -> Evergreen.V26.Internal.Shape.Shape coordinates_new
migrate_Internal_Shape_Shape migrate_coordinates old =
    case old of
        Evergreen.V25.Internal.Shape.Convex p0 ->
            Evergreen.V26.Internal.Shape.Convex (p0 |> migrate_Shapes_Convex_Convex)

        Evergreen.V25.Internal.Shape.Plane p0 ->
            Evergreen.V26.Internal.Shape.Plane (p0 |> migrate_Shapes_Plane_Plane)

        Evergreen.V25.Internal.Shape.Sphere p0 ->
            Evergreen.V26.Internal.Shape.Sphere (p0 |> migrate_Shapes_Sphere_Sphere)

        Evergreen.V25.Internal.Shape.Particle p0 ->
            Evergreen.V26.Internal.Shape.Particle (p0 |> migrate_Internal_Vector3_Vec3)


migrate_Internal_Transform3d_Orientation3d : Evergreen.V25.Internal.Transform3d.Orientation3d -> Evergreen.V26.Internal.Transform3d.Orientation3d
migrate_Internal_Transform3d_Orientation3d old =
    case old of
        Evergreen.V25.Internal.Transform3d.Orientation3d p0 p1 p2 p3 ->
            Evergreen.V26.Internal.Transform3d.Orientation3d p0 p1 p2 p3


migrate_Internal_Transform3d_Transform3d : (coordinates_old -> coordinates_new) -> (defines_old -> defines_new) -> Evergreen.V25.Internal.Transform3d.Transform3d coordinates_old defines_old -> Evergreen.V26.Internal.Transform3d.Transform3d coordinates_new defines_new
migrate_Internal_Transform3d_Transform3d migrate_coordinates migrate_defines old =
    case old of
        Evergreen.V25.Internal.Transform3d.Transform3d p0 p1 ->
            Evergreen.V26.Internal.Transform3d.Transform3d (p0 |> migrate_Internal_Vector3_Vec3)
                (p1 |> migrate_Internal_Transform3d_Orientation3d)


migrate_Internal_Vector3_Vec3 : Evergreen.V25.Internal.Vector3.Vec3 -> Evergreen.V26.Internal.Vector3.Vec3
migrate_Internal_Vector3_Vec3 old =
    old


migrate_Internal_World_Protected : (data_old -> data_new) -> Evergreen.V25.Internal.World.Protected data_old -> Evergreen.V26.Internal.World.Protected data_new
migrate_Internal_World_Protected migrate_data old =
    case old of
        Evergreen.V25.Internal.World.Protected p0 ->
            Evergreen.V26.Internal.World.Protected (p0 |> migrate_Internal_World_World migrate_data)


migrate_Internal_World_World : (data_old -> data_new) -> Evergreen.V25.Internal.World.World data_old -> Evergreen.V26.Internal.World.World data_new
migrate_Internal_World_World migrate_data old =
    { bodies = old.bodies |> List.map (migrate_Internal_Body_Body migrate_data)
    , constraints = old.constraints |> List.map migrate_Internal_Constraint_ConstraintGroup
    , freeIds = old.freeIds
    , nextBodyId = old.nextBodyId
    , gravity = old.gravity |> migrate_Internal_Vector3_Vec3
    , contactGroups = old.contactGroups |> List.map (migrate_Internal_Contact_ContactGroup migrate_data)
    , simulatedBodies = old.simulatedBodies |> Array.map (migrate_Internal_Body_Body migrate_data)
    }


migrate_Physics_Coordinates_BodyCoordinates : Evergreen.V25.Physics.Coordinates.BodyCoordinates -> Evergreen.V26.Physics.Coordinates.BodyCoordinates
migrate_Physics_Coordinates_BodyCoordinates old =
    case old of
        Evergreen.V25.Physics.Coordinates.BodyCoordinates ->
            Evergreen.V26.Physics.Coordinates.BodyCoordinates


migrate_Physics_Coordinates_WorldCoordinates : Evergreen.V25.Physics.Coordinates.WorldCoordinates -> Evergreen.V26.Physics.Coordinates.WorldCoordinates
migrate_Physics_Coordinates_WorldCoordinates old =
    case old of
        Evergreen.V25.Physics.Coordinates.WorldCoordinates ->
            Evergreen.V26.Physics.Coordinates.WorldCoordinates


migrate_Physics_World_World : (data_old -> data_new) -> Evergreen.V25.Physics.World.World data_old -> Evergreen.V26.Physics.World.World data_new
migrate_Physics_World_World migrate_data old =
    old |> migrate_Internal_World_Protected migrate_data


migrate_Scene3d_Material_Texture : (value_old -> value_new) -> Evergreen.V25.Scene3d.Material.Texture value_old -> Evergreen.V26.Scene3d.Material.Texture value_new
migrate_Scene3d_Material_Texture migrate_value old =
    old |> migrate_Scene3d_Types_Texture migrate_value


migrate_Scene3d_Types_Texture : (value_old -> value_new) -> Evergreen.V25.Scene3d.Types.Texture value_old -> Evergreen.V26.Scene3d.Types.Texture value_new
migrate_Scene3d_Types_Texture migrate_value old =
    case old of
        Evergreen.V25.Scene3d.Types.Constant p0 ->
            Evergreen.V26.Scene3d.Types.Constant (p0 |> migrate_value)

        Evergreen.V25.Scene3d.Types.Texture p0 ->
            Evergreen.V26.Scene3d.Types.Texture p0


migrate_Shapes_Convex_Convex : Evergreen.V25.Shapes.Convex.Convex -> Evergreen.V26.Shapes.Convex.Convex
migrate_Shapes_Convex_Convex old =
    { faces = old.faces
    , vertices = old.vertices
    , uniqueEdges = old.uniqueEdges
    , uniqueNormals = old.uniqueNormals
    , position = old.position |> migrate_Internal_Vector3_Vec3
    , inertia = old.inertia |> migrate_Internal_Matrix3_Mat3
    , volume = old.volume
    }


migrate_Shapes_Plane_Plane : Evergreen.V25.Shapes.Plane.Plane -> Evergreen.V26.Shapes.Plane.Plane
migrate_Shapes_Plane_Plane old =
    { normal = old.normal |> migrate_Internal_Vector3_Vec3
    , position = old.position |> migrate_Internal_Vector3_Vec3
    }


migrate_Shapes_Sphere_Sphere : Evergreen.V25.Shapes.Sphere.Sphere -> Evergreen.V26.Shapes.Sphere.Sphere
migrate_Shapes_Sphere_Sphere old =
    { radius = old.radius
    , position = old.position |> migrate_Internal_Vector3_Vec3
    , volume = old.volume
    , inertia = old.inertia |> migrate_Internal_Matrix3_Mat3
    }


migrate_Types_BodyType : Evergreen.V25.Types.BodyType -> Evergreen.V26.Types.BodyType
migrate_Types_BodyType old =
    case old of
        Evergreen.V25.Types.NotPlayer ->
            Evergreen.V26.Types.NotPlayer

        Evergreen.V25.Types.Player ->
            Evergreen.V26.Types.Player


migrate_Types_ButtonState : Evergreen.V25.Types.ButtonState -> Evergreen.V26.Types.ButtonState
migrate_Types_ButtonState old =
    case old of
        Evergreen.V25.Types.Up ->
            Evergreen.V26.Types.Up

        Evergreen.V25.Types.Down ->
            Evergreen.V26.Types.Down


migrate_Types_ContactType : Evergreen.V25.Types.ContactType -> Evergreen.V26.Types.ContactType
migrate_Types_ContactType old =
    case old of
        Evergreen.V25.Types.Touch ->
            Evergreen.V26.Types.Touch

        Evergreen.V25.Types.Mouse ->
            Evergreen.V26.Types.Mouse


migrate_Types_FrontendModel : Evergreen.V25.Types.FrontendModel -> Evergreen.V26.Types.FrontendModel
migrate_Types_FrontendModel old =
    case old of
        Evergreen.V25.Types.Loading p0 ->
            Evergreen.V26.Types.Loading
                { colorTexture = p0.colorTexture |> Maybe.map (migrate_Scene3d_Material_Texture identity)
                , roughnessTexture = p0.roughnessTexture |> Maybe.map (migrate_Scene3d_Material_Texture identity)
                , width = 0
                , height = 0
                }

        Evergreen.V25.Types.Loaded p0 ->
            Evergreen.V26.Types.Loaded
                { colorTexture = p0.colorTexture |> migrate_Scene3d_Material_Texture identity
                , roughnessTexture = p0.roughnessTexture |> migrate_Scene3d_Material_Texture identity
                , width = p0.width
                , height = p0.height
                , cameraAngle = p0.cameraAngle |> migrate_Direction3dWire_Direction3dWire migrate_Physics_Coordinates_WorldCoordinates
                , leftKey = p0.leftKey |> migrate_Types_ButtonState
                , rightKey = p0.rightKey |> migrate_Types_ButtonState
                , upKey = p0.upKey |> migrate_Types_ButtonState
                , downKey = p0.downKey |> migrate_Types_ButtonState
                , mouseButtonState = p0.mouseButtonState |> migrate_Types_ButtonState
                , touches = p0.touches |> migrate_Types_TouchContact
                , world = p0.world |> migrate_Physics_World_World migrate_Types_WorldData
                , joystickPosition =
                    p0.joystickPosition
                        |> (\rec1 -> rec1)
                , viewAngleDelta = p0.viewAngleDelta
                , lightPosition = p0.lightPosition
                , lastContact = p0.lastContact |> migrate_Types_ContactType
                , pointerCapture = p0.pointerCapture |> migrate_Types_PointerCapture
                }

        Evergreen.V25.Types.Errored p0 ->
            Evergreen.V26.Types.Errored p0


migrate_Types_PointerCapture : Evergreen.V25.Types.PointerCapture -> Evergreen.V26.Types.PointerCapture
migrate_Types_PointerCapture old =
    case old of
        Evergreen.V25.Types.PointerLocked ->
            Evergreen.V26.Types.PointerLocked

        Evergreen.V25.Types.PointerNotLocked ->
            Evergreen.V26.Types.PointerNotLocked


migrate_Types_TouchContact : Evergreen.V25.Types.TouchContact -> Evergreen.V26.Types.TouchContact
migrate_Types_TouchContact old =
    case old of
        Evergreen.V25.Types.OneFinger p0 ->
            Evergreen.V26.Types.OneFinger p0

        Evergreen.V25.Types.NotOneFinger ->
            Evergreen.V26.Types.NotOneFinger


migrate_Types_WorldData : Evergreen.V25.Types.WorldData -> Evergreen.V26.Types.WorldData
migrate_Types_WorldData old =
    { bodyType = old.bodyType |> migrate_Types_BodyType
    }
