module Evergreen.Migrate.V29 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Array
import Evergreen.V28.Direction3d
import Evergreen.V28.Geometry.Types
import Evergreen.V28.Internal.Body
import Evergreen.V28.Internal.Constraint
import Evergreen.V28.Internal.Contact
import Evergreen.V28.Internal.Material
import Evergreen.V28.Internal.Matrix3
import Evergreen.V28.Internal.Shape
import Evergreen.V28.Internal.Transform3d
import Evergreen.V28.Internal.Vector3
import Evergreen.V28.Internal.World
import Evergreen.V28.Physics.Coordinates
import Evergreen.V28.Physics.World
import Evergreen.V28.Scene3d.Material
import Evergreen.V28.Scene3d.Types
import Evergreen.V28.Shapes.Convex
import Evergreen.V28.Shapes.Plane
import Evergreen.V28.Shapes.Sphere
import Evergreen.V28.Types
import Evergreen.V29.Direction3d
import Evergreen.V29.Geometry.Types
import Evergreen.V29.Internal.Body
import Evergreen.V29.Internal.Constraint
import Evergreen.V29.Internal.Contact
import Evergreen.V29.Internal.Material
import Evergreen.V29.Internal.Matrix3
import Evergreen.V29.Internal.Shape
import Evergreen.V29.Internal.Transform3d
import Evergreen.V29.Internal.Vector3
import Evergreen.V29.Internal.World
import Evergreen.V29.Physics.Coordinates
import Evergreen.V29.Physics.World
import Evergreen.V29.Scene3d.Material
import Evergreen.V29.Scene3d.Types
import Evergreen.V29.Shapes.Convex
import Evergreen.V29.Shapes.Plane
import Evergreen.V29.Shapes.Sphere
import Evergreen.V29.Types
import Evergreen.V29.Vector2d
import Lamdera.Migrations exposing (..)
import Length
import List
import Maybe
import Pixels exposing (Pixels)
import Point3d
import Vector2d


frontendModel : Evergreen.V28.Types.FrontendModel -> ModelMigration Evergreen.V29.Types.FrontendModel Evergreen.V29.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V28.Types.BackendModel -> ModelMigration Evergreen.V29.Types.BackendModel Evergreen.V29.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V28.Types.FrontendMsg -> MsgMigration Evergreen.V29.Types.FrontendMsg Evergreen.V29.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V28.Types.ToBackend -> MsgMigration Evergreen.V29.Types.ToBackend Evergreen.V29.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V28.Types.BackendMsg -> MsgMigration Evergreen.V29.Types.BackendMsg Evergreen.V29.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V28.Types.ToFrontend -> MsgMigration Evergreen.V29.Types.ToFrontend Evergreen.V29.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V28.Types.FrontendModel -> Evergreen.V29.Types.FrontendModel
migrate_Types_FrontendModel old =
    { width = old.width |> Basics.round |> Pixels.int
    , height = old.height |> Basics.round |> Pixels.int
    , cameraAngle = old.cameraAngle |> migrate_Direction3d_Direction3d migrate_Physics_Coordinates_WorldCoordinates
    , leftKey = old.leftKey |> migrate_Types_ButtonState
    , rightKey = old.rightKey |> migrate_Types_ButtonState
    , upKey = old.upKey |> migrate_Types_ButtonState
    , downKey = old.downKey |> migrate_Types_ButtonState
    , mouseButtonState = old.mouseButtonState |> migrate_Types_ButtonState
    , touches = old.touches |> migrate_Types_TouchContact
    , world = old.world |> migrate_Physics_World_World migrate_Types_WorldData
    , joystickOffset =
        let
            { x, y } =
                old.joystickPosition
        in
        Evergreen.V29.Geometry.Types.Vector2d { x = x, y = y }
    , viewPivotDelta = Evergreen.V29.Geometry.Types.Vector2d { x = 0, y = 0 }
    , lightPosition =
        let
            ( x, y, z ) =
                old.lightPosition
        in
        Evergreen.V29.Geometry.Types.Point3d { x = x, y = y, z = z }
    , lastContact = old.lastContact |> migrate_Types_ContactType
    , pointerCapture = old.pointerCapture |> migrate_Types_PointerCapture
    , playerColorTexture = old.playerColorTexture |> Maybe.map (migrate_Scene3d_Material_Texture identity)
    , playerRoughnessTexture = old.playerRoughnessTexture |> Maybe.map (migrate_Scene3d_Material_Texture identity)
    }


migrate_Direction3d_Direction3d : (coordinates_old -> coordinates_new) -> Evergreen.V28.Direction3d.Direction3d coordinates_old -> Evergreen.V29.Direction3d.Direction3d coordinates_new
migrate_Direction3d_Direction3d migrate_coordinates old =
    old |> migrate_Geometry_Types_Direction3d migrate_coordinates


migrate_Geometry_Types_Direction3d : (coordinates_old -> coordinates_new) -> Evergreen.V28.Geometry.Types.Direction3d coordinates_old -> Evergreen.V29.Geometry.Types.Direction3d coordinates_new
migrate_Geometry_Types_Direction3d migrate_coordinates old =
    case old of
        Evergreen.V28.Geometry.Types.Direction3d p0 ->
            Evergreen.V29.Geometry.Types.Direction3d p0


migrate_Internal_Body_Body : (data_old -> data_new) -> Evergreen.V28.Internal.Body.Body data_old -> Evergreen.V29.Internal.Body.Body data_new
migrate_Internal_Body_Body migrate_data old =
    { id = old.id
    , data = old.data |> migrate_data
    , material = old.material |> migrate_Internal_Material_Material
    , transform3d =
        old.transform3d
            |> migrate_Internal_Transform3d_Transform3d migrate_Physics_Coordinates_WorldCoordinates
                (\rec ->
                    { defines = rec.defines |> migrate_Internal_Shape_CenterOfMassCoordinates
                    }
                )
    , centerOfMassTransform3d =
        old.centerOfMassTransform3d
            |> migrate_Internal_Transform3d_Transform3d migrate_Physics_Coordinates_BodyCoordinates
                (\rec ->
                    { defines = rec.defines |> migrate_Internal_Shape_CenterOfMassCoordinates
                    }
                )
    , velocity = old.velocity |> migrate_Internal_Vector3_Vec3
    , angularVelocity = old.angularVelocity |> migrate_Internal_Vector3_Vec3
    , mass = old.mass
    , shapes = old.shapes |> List.map (migrate_Internal_Shape_Shape migrate_Internal_Shape_CenterOfMassCoordinates)
    , worldShapes = old.worldShapes |> List.map (migrate_Internal_Shape_Shape migrate_Physics_Coordinates_WorldCoordinates)
    , force = old.force |> migrate_Internal_Vector3_Vec3
    , torque = old.torque |> migrate_Internal_Vector3_Vec3
    , boundingSphereRadius = old.boundingSphereRadius
    , linearDamping = old.linearDamping
    , angularDamping = old.angularDamping
    , invMass = old.invMass
    , invInertia = old.invInertia |> migrate_Internal_Matrix3_Mat3
    , invInertiaWorld = old.invInertiaWorld |> migrate_Internal_Matrix3_Mat3
    }


migrate_Internal_Constraint_Constraint : (coordinates_old -> coordinates_new) -> Evergreen.V28.Internal.Constraint.Constraint coordinates_old -> Evergreen.V29.Internal.Constraint.Constraint coordinates_new
migrate_Internal_Constraint_Constraint migrate_coordinates old =
    case old of
        Evergreen.V28.Internal.Constraint.PointToPoint p0 p1 ->
            Evergreen.V29.Internal.Constraint.PointToPoint (p0 |> migrate_Internal_Vector3_Vec3)
                (p1 |> migrate_Internal_Vector3_Vec3)

        Evergreen.V28.Internal.Constraint.Hinge p0 p1 p2 p3 ->
            Evergreen.V29.Internal.Constraint.Hinge (p0 |> migrate_Internal_Vector3_Vec3)
                (p1 |> migrate_Internal_Vector3_Vec3)
                (p2 |> migrate_Internal_Vector3_Vec3)
                (p3 |> migrate_Internal_Vector3_Vec3)

        Evergreen.V28.Internal.Constraint.Lock p0 p1 p2 p3 p4 p5 p6 p7 ->
            Evergreen.V29.Internal.Constraint.Lock (p0 |> migrate_Internal_Vector3_Vec3)
                (p1 |> migrate_Internal_Vector3_Vec3)
                (p2 |> migrate_Internal_Vector3_Vec3)
                (p3 |> migrate_Internal_Vector3_Vec3)
                (p4 |> migrate_Internal_Vector3_Vec3)
                (p5 |> migrate_Internal_Vector3_Vec3)
                (p6 |> migrate_Internal_Vector3_Vec3)
                (p7 |> migrate_Internal_Vector3_Vec3)

        Evergreen.V28.Internal.Constraint.Distance p0 ->
            Evergreen.V29.Internal.Constraint.Distance p0


migrate_Internal_Constraint_ConstraintGroup : Evergreen.V28.Internal.Constraint.ConstraintGroup -> Evergreen.V29.Internal.Constraint.ConstraintGroup
migrate_Internal_Constraint_ConstraintGroup old =
    { bodyId1 = old.bodyId1
    , bodyId2 = old.bodyId2
    , constraints = old.constraints |> List.map (migrate_Internal_Constraint_Constraint migrate_Internal_Shape_CenterOfMassCoordinates)
    }


migrate_Internal_Contact_ContactGroup : (data_old -> data_new) -> Evergreen.V28.Internal.Contact.ContactGroup data_old -> Evergreen.V29.Internal.Contact.ContactGroup data_new
migrate_Internal_Contact_ContactGroup migrate_data old =
    { body1 = old.body1 |> migrate_Internal_Body_Body migrate_data
    , body2 = old.body2 |> migrate_Internal_Body_Body migrate_data
    , contacts = old.contacts
    }


migrate_Internal_Material_Material : Evergreen.V28.Internal.Material.Material -> Evergreen.V29.Internal.Material.Material
migrate_Internal_Material_Material old =
    old


migrate_Internal_Matrix3_Mat3 : Evergreen.V28.Internal.Matrix3.Mat3 -> Evergreen.V29.Internal.Matrix3.Mat3
migrate_Internal_Matrix3_Mat3 old =
    old


migrate_Internal_Shape_CenterOfMassCoordinates : Evergreen.V28.Internal.Shape.CenterOfMassCoordinates -> Evergreen.V29.Internal.Shape.CenterOfMassCoordinates
migrate_Internal_Shape_CenterOfMassCoordinates old =
    case old of
        Evergreen.V28.Internal.Shape.CenterOfMassCoordinates ->
            Evergreen.V29.Internal.Shape.CenterOfMassCoordinates


migrate_Internal_Shape_Shape : (coordinates_old -> coordinates_new) -> Evergreen.V28.Internal.Shape.Shape coordinates_old -> Evergreen.V29.Internal.Shape.Shape coordinates_new
migrate_Internal_Shape_Shape migrate_coordinates old =
    case old of
        Evergreen.V28.Internal.Shape.Convex p0 ->
            Evergreen.V29.Internal.Shape.Convex (p0 |> migrate_Shapes_Convex_Convex)

        Evergreen.V28.Internal.Shape.Plane p0 ->
            Evergreen.V29.Internal.Shape.Plane (p0 |> migrate_Shapes_Plane_Plane)

        Evergreen.V28.Internal.Shape.Sphere p0 ->
            Evergreen.V29.Internal.Shape.Sphere (p0 |> migrate_Shapes_Sphere_Sphere)

        Evergreen.V28.Internal.Shape.Particle p0 ->
            Evergreen.V29.Internal.Shape.Particle (p0 |> migrate_Internal_Vector3_Vec3)


migrate_Internal_Transform3d_Orientation3d : Evergreen.V28.Internal.Transform3d.Orientation3d -> Evergreen.V29.Internal.Transform3d.Orientation3d
migrate_Internal_Transform3d_Orientation3d old =
    case old of
        Evergreen.V28.Internal.Transform3d.Orientation3d p0 p1 p2 p3 ->
            Evergreen.V29.Internal.Transform3d.Orientation3d p0 p1 p2 p3


migrate_Internal_Transform3d_Transform3d : (coordinates_old -> coordinates_new) -> (defines_old -> defines_new) -> Evergreen.V28.Internal.Transform3d.Transform3d coordinates_old defines_old -> Evergreen.V29.Internal.Transform3d.Transform3d coordinates_new defines_new
migrate_Internal_Transform3d_Transform3d migrate_coordinates migrate_defines old =
    case old of
        Evergreen.V28.Internal.Transform3d.Transform3d p0 p1 ->
            Evergreen.V29.Internal.Transform3d.Transform3d (p0 |> migrate_Internal_Vector3_Vec3)
                (p1 |> migrate_Internal_Transform3d_Orientation3d)


migrate_Internal_Vector3_Vec3 : Evergreen.V28.Internal.Vector3.Vec3 -> Evergreen.V29.Internal.Vector3.Vec3
migrate_Internal_Vector3_Vec3 old =
    old


migrate_Internal_World_Protected : (data_old -> data_new) -> Evergreen.V28.Internal.World.Protected data_old -> Evergreen.V29.Internal.World.Protected data_new
migrate_Internal_World_Protected migrate_data old =
    case old of
        Evergreen.V28.Internal.World.Protected p0 ->
            Evergreen.V29.Internal.World.Protected (p0 |> migrate_Internal_World_World migrate_data)


migrate_Internal_World_World : (data_old -> data_new) -> Evergreen.V28.Internal.World.World data_old -> Evergreen.V29.Internal.World.World data_new
migrate_Internal_World_World migrate_data old =
    { bodies = old.bodies |> List.map (migrate_Internal_Body_Body migrate_data)
    , constraints = old.constraints |> List.map migrate_Internal_Constraint_ConstraintGroup
    , freeIds = old.freeIds
    , nextBodyId = old.nextBodyId
    , gravity = old.gravity |> migrate_Internal_Vector3_Vec3
    , contactGroups = old.contactGroups |> List.map (migrate_Internal_Contact_ContactGroup migrate_data)
    , simulatedBodies = old.simulatedBodies |> Array.map (migrate_Internal_Body_Body migrate_data)
    }


migrate_Physics_Coordinates_BodyCoordinates : Evergreen.V28.Physics.Coordinates.BodyCoordinates -> Evergreen.V29.Physics.Coordinates.BodyCoordinates
migrate_Physics_Coordinates_BodyCoordinates old =
    case old of
        Evergreen.V28.Physics.Coordinates.BodyCoordinates ->
            Evergreen.V29.Physics.Coordinates.BodyCoordinates


migrate_Physics_Coordinates_WorldCoordinates : Evergreen.V28.Physics.Coordinates.WorldCoordinates -> Evergreen.V29.Physics.Coordinates.WorldCoordinates
migrate_Physics_Coordinates_WorldCoordinates old =
    case old of
        Evergreen.V28.Physics.Coordinates.WorldCoordinates ->
            Evergreen.V29.Physics.Coordinates.WorldCoordinates


migrate_Physics_World_World : (data_old -> data_new) -> Evergreen.V28.Physics.World.World data_old -> Evergreen.V29.Physics.World.World data_new
migrate_Physics_World_World migrate_data old =
    old |> migrate_Internal_World_Protected migrate_data


migrate_Scene3d_Material_Texture : (value_old -> value_new) -> Evergreen.V28.Scene3d.Material.Texture value_old -> Evergreen.V29.Scene3d.Material.Texture value_new
migrate_Scene3d_Material_Texture migrate_value old =
    old |> migrate_Scene3d_Types_Texture migrate_value


migrate_Scene3d_Types_Texture : (value_old -> value_new) -> Evergreen.V28.Scene3d.Types.Texture value_old -> Evergreen.V29.Scene3d.Types.Texture value_new
migrate_Scene3d_Types_Texture migrate_value old =
    case old of
        Evergreen.V28.Scene3d.Types.Constant p0 ->
            Evergreen.V29.Scene3d.Types.Constant (p0 |> migrate_value)

        Evergreen.V28.Scene3d.Types.Texture p0 ->
            Evergreen.V29.Scene3d.Types.Texture p0


migrate_Shapes_Convex_Convex : Evergreen.V28.Shapes.Convex.Convex -> Evergreen.V29.Shapes.Convex.Convex
migrate_Shapes_Convex_Convex old =
    { faces = old.faces
    , vertices = old.vertices
    , uniqueEdges = old.uniqueEdges
    , uniqueNormals = old.uniqueNormals
    , position = old.position |> migrate_Internal_Vector3_Vec3
    , inertia = old.inertia |> migrate_Internal_Matrix3_Mat3
    , volume = old.volume
    }


migrate_Shapes_Plane_Plane : Evergreen.V28.Shapes.Plane.Plane -> Evergreen.V29.Shapes.Plane.Plane
migrate_Shapes_Plane_Plane old =
    { normal = old.normal |> migrate_Internal_Vector3_Vec3
    , position = old.position |> migrate_Internal_Vector3_Vec3
    }


migrate_Shapes_Sphere_Sphere : Evergreen.V28.Shapes.Sphere.Sphere -> Evergreen.V29.Shapes.Sphere.Sphere
migrate_Shapes_Sphere_Sphere old =
    { radius = old.radius
    , position = old.position |> migrate_Internal_Vector3_Vec3
    , volume = old.volume
    , inertia = old.inertia |> migrate_Internal_Matrix3_Mat3
    }


migrate_Types_ArrowKey : Evergreen.V28.Types.ArrowKey -> Evergreen.V29.Types.ArrowKey
migrate_Types_ArrowKey old =
    case old of
        Evergreen.V28.Types.UpKey ->
            Evergreen.V29.Types.UpKey

        Evergreen.V28.Types.DownKey ->
            Evergreen.V29.Types.DownKey

        Evergreen.V28.Types.LeftKey ->
            Evergreen.V29.Types.LeftKey

        Evergreen.V28.Types.RightKey ->
            Evergreen.V29.Types.RightKey


migrate_Types_BodyType : Evergreen.V28.Types.BodyType -> Evergreen.V29.Types.BodyType
migrate_Types_BodyType old =
    case old of
        Evergreen.V28.Types.Static ->
            Evergreen.V29.Types.Static

        Evergreen.V28.Types.Dynamic ->
            Evergreen.V29.Types.Dynamic

        Evergreen.V28.Types.Player ->
            Evergreen.V29.Types.Player


migrate_Types_ButtonState : Evergreen.V28.Types.ButtonState -> Evergreen.V29.Types.ButtonState
migrate_Types_ButtonState old =
    case old of
        Evergreen.V28.Types.Up ->
            Evergreen.V29.Types.Up

        Evergreen.V28.Types.Down ->
            Evergreen.V29.Types.Down


migrate_Types_ContactType : Evergreen.V28.Types.ContactType -> Evergreen.V29.Types.ContactType
migrate_Types_ContactType old =
    case old of
        Evergreen.V28.Types.Touch ->
            Evergreen.V29.Types.Touch

        Evergreen.V28.Types.Mouse ->
            Evergreen.V29.Types.Mouse


migrate_Types_FrontendMsg : Evergreen.V28.Types.FrontendMsg -> Evergreen.V29.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V28.Types.WindowResized p0 p1 ->
            Evergreen.V29.Types.WindowResized
                (p0 |> Basics.round |> Pixels.int)
                (p1 |> Basics.round |> Pixels.int)

        Evergreen.V28.Types.Tick p0 ->
            Evergreen.V29.Types.Tick p0

        Evergreen.V28.Types.MouseMoved p0 p1 ->
            Evergreen.V29.Types.MouseMoved (Evergreen.V29.Geometry.Types.Vector2d { x = p0, y = p1 })

        Evergreen.V28.Types.MouseDown ->
            Evergreen.V29.Types.MouseDown

        Evergreen.V28.Types.MouseUp ->
            Evergreen.V29.Types.MouseUp

        Evergreen.V28.Types.ArrowKeyChanged p0 p1 ->
            Evergreen.V29.Types.ArrowKeyChanged (p0 |> migrate_Types_ArrowKey)
                (p1 |> migrate_Types_ButtonState)

        Evergreen.V28.Types.TouchesChanged p0 ->
            Evergreen.V29.Types.TouchesChanged (p0 |> migrate_Types_TouchContact)

        Evergreen.V28.Types.JoystickTouchChanged p0 ->
            Evergreen.V29.Types.JoystickTouchChanged (p0 |> migrate_Types_TouchContact)

        Evergreen.V28.Types.ShootClicked ->
            Evergreen.V29.Types.ShootClicked

        Evergreen.V28.Types.GotPointerLock ->
            Evergreen.V29.Types.GotPointerLock

        Evergreen.V28.Types.LostPointerLock ->
            Evergreen.V29.Types.LostPointerLock

        Evergreen.V28.Types.GotColorTexture p0 ->
            Evergreen.V29.Types.GotColorTexture (p0 |> Result.map (migrate_Scene3d_Material_Texture identity))

        Evergreen.V28.Types.GotRoughnessTexture p0 ->
            Evergreen.V29.Types.GotRoughnessTexture (p0 |> Result.map (migrate_Scene3d_Material_Texture identity))

        Evergreen.V28.Types.NoOpFrontendMsg ->
            Evergreen.V29.Types.NoOpFrontendMsg


migrate_Types_PointerCapture : Evergreen.V28.Types.PointerCapture -> Evergreen.V29.Types.PointerCapture
migrate_Types_PointerCapture old =
    case old of
        Evergreen.V28.Types.PointerLocked ->
            Evergreen.V29.Types.PointerLocked

        Evergreen.V28.Types.PointerNotLocked ->
            Evergreen.V29.Types.PointerNotLocked


migrate_Types_TouchContact : Evergreen.V28.Types.TouchContact -> Evergreen.V29.Types.TouchContact
migrate_Types_TouchContact old =
    case old of
        Evergreen.V28.Types.OneFinger p0 ->
            Evergreen.V29.Types.OneFinger
                { identifier = p0.identifier
                , screenPos =
                    let
                        ( x, y ) =
                            p0.screenPos
                    in
                    Evergreen.V29.Geometry.Types.Point2d { x = x, y = y }
                }

        Evergreen.V28.Types.NotOneFinger ->
            Evergreen.V29.Types.NotOneFinger


migrate_Types_WorldData : Evergreen.V28.Types.WorldData -> Evergreen.V29.Types.WorldData
migrate_Types_WorldData old =
    old |> migrate_Types_BodyType
