module Evergreen.Migrate.V4 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V1.Types
import Evergreen.V4.Direction3dWire
import Evergreen.V4.Types
import Lamdera.Migrations exposing (..)
import Math.Vector3


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V4.Types.FrontendModel Evergreen.V4.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V4.Types.BackendModel Evergreen.V4.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V4.Types.FrontendMsg Evergreen.V4.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V4.Types.ToBackend Evergreen.V4.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V4.Types.BackendMsg Evergreen.V4.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V4.Types.ToFrontend Evergreen.V4.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V4.Types.FrontendModel
migrate_Types_FrontendModel old =
    { width = old.width
    , height = old.height
    , mousePosition = (Unimplemented {- Type `(Float, Float)` was added in V4. I need you to set a default value. -})
    , leftKey = (Unimplemented {- Type `Evergreen.V4.Types.ButtonState` was added in V4. I need you to set a default value. -})
    , rightKey = (Unimplemented {- Type `Evergreen.V4.Types.ButtonState` was added in V4. I need you to set a default value. -})
    , upKey = (Unimplemented {- Type `Evergreen.V4.Types.ButtonState` was added in V4. I need you to set a default value. -})
    , downKey = (Unimplemented {- Type `Evergreen.V4.Types.ButtonState` was added in V4. I need you to set a default value. -})
    , cameraAngle = old.cameraAngle |> migrate_Direction3dWire_Direction3dWire
    , cameraPosition = (Unimplemented {- Type `(Float, Float, Float)` was added in V4. I need you to set a default value. -})
    , mouseButtonState = old.mouseButtonState |> migrate_Types_ButtonState
    , lightPosition = (Unimplemented {- Type `(Float, Float, Float)` was added in V4. I need you to set a default value. -})
    , cameraDistance = (Unimplemented {- Field of type `Float` was removed in V4. I need you to do something with the `old.cameraDistance` value if you wish to keep the data, then remove this line. -})
    , cameraUp = (Unimplemented {- Field of type `elm-explorations/linear-algebra:Math.Vector3.Vec3` was removed in V4. I need you to do something with the `old.cameraUp` value if you wish to keep the data, then remove this line. -})
    }


migrate_Direction3dWire_Direction3dWire : Math.Vector3.Direction3dWire -> Evergreen.V4.Direction3dWire.Direction3dWire coordinates_new
migrate_Direction3dWire_Direction3dWire old =
    case old of
        Math.Vector3.Vec3 ->
            (Unimplemented
             {- `Vec3` was removed or renamed in V4 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Math.Vector3.Vec3 value in a migration.
                See https://lamdera.com/tips/modified-custom-type for more info.
             -}
            )

        notices ->
            {- @NOTICE `Direction3dWire Float Float Float` was added in V4.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://lamdera.com/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})


migrate_Types_ButtonState : Evergreen.V1.Types.ButtonState -> Evergreen.V4.Types.ButtonState
migrate_Types_ButtonState old =
    case old of
        Evergreen.V1.Types.Up ->
            Evergreen.V4.Types.Up

        Evergreen.V1.Types.Down ->
            Evergreen.V4.Types.Down


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V4.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.WindowResized p0 p1 ->
            Evergreen.V4.Types.WindowResized p0 p1

        Evergreen.V1.Types.MouseMoved p0 p1 ->
            Evergreen.V4.Types.MouseMoved p0 p1

        Evergreen.V1.Types.MouseDown ->
            Evergreen.V4.Types.MouseDown

        Evergreen.V1.Types.MouseUp ->
            Evergreen.V4.Types.MouseUp

        Evergreen.V1.Types.NoOpFrontendMsg ->
            Evergreen.V4.Types.NoOpFrontendMsg

        notices ->
            {- @NOTICE `Tick Float` was added in V4.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://lamdera.com/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `ArrowKeyChanged ArrowKey ButtonState` was added in V4.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://lamdera.com/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})
