module Evergreen.Migrate.V4 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V1.Types
import Evergreen.V4.Direction3dWire
import Evergreen.V4.Types
import Lamdera.Migrations exposing (..)
import Math.Vector3


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V4.Types.FrontendModel Evergreen.V4.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V4.Types.BackendModel Evergreen.V4.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V4.Types.FrontendMsg Evergreen.V4.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V4.Types.ToBackend Evergreen.V4.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V4.Types.BackendMsg Evergreen.V4.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V4.Types.ToFrontend Evergreen.V4.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V4.Types.FrontendModel
migrate_Types_FrontendModel old =
    { width = old.width
    , height = old.height
    , mousePosition = ( 0, 0 )
    , leftKey = Evergreen.V4.Types.Up
    , rightKey = Evergreen.V4.Types.Up
    , upKey = Evergreen.V4.Types.Up
    , downKey = Evergreen.V4.Types.Up
    , cameraAngle = old.cameraAngle |> migrate_Direction3dWire_Direction3dWire
    , cameraPosition = ( 2, 2, 2 )
    , mouseButtonState = old.mouseButtonState |> migrate_Types_ButtonState
    , lightPosition = ( 3, 3, 3 )
    }


migrate_Direction3dWire_Direction3dWire : Math.Vector3.Vec3 -> Evergreen.V4.Direction3dWire.Direction3dWire coordinates_new
migrate_Direction3dWire_Direction3dWire old =
    Math.Vector3.toRecord old |> (\{ x, y, z } -> Evergreen.V4.Direction3dWire.Direction3dWire x y z)


migrate_Types_ButtonState : Evergreen.V1.Types.MouseButtonState -> Evergreen.V4.Types.ButtonState
migrate_Types_ButtonState old =
    case old of
        Evergreen.V1.Types.Up ->
            Evergreen.V4.Types.Up

        Evergreen.V1.Types.Down ->
            Evergreen.V4.Types.Down


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V4.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.WindowResized p0 p1 ->
            Evergreen.V4.Types.WindowResized p0 p1

        Evergreen.V1.Types.MouseMoved p0 p1 ->
            Evergreen.V4.Types.MouseMoved p0 p1

        Evergreen.V1.Types.MouseDown ->
            Evergreen.V4.Types.MouseDown

        Evergreen.V1.Types.MouseUp ->
            Evergreen.V4.Types.MouseUp

        Evergreen.V1.Types.NoOpFrontendMsg ->
            Evergreen.V4.Types.NoOpFrontendMsg
